services:

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      
    environment:
      AUTOR: Daniel
      DB_HOST: db
      DB_USER: usuario
      DB_PASS: password123
      DB_NAME: notasdb
    networks:
      - redlocal

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: notasdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - redlocal

volumes:
  pgdata:

networks:
  redlocal: